export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
  }
  
  export default function Layout({ children }) {
    return (
      <html lang="en">
        <head>
          {/* You can use the metadata here */}
          <meta name="description" content={metadata.description} />
        </head>
        <body>{children}</body>
      </html>
    )
  }
  